<?php

namespace ContainerZYoI7Bx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hk1DqdAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hk1DqdA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hk1DqdA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formulaRepository' => ['privates', 'App\\Repository\\FormulaRepository', 'getFormulaRepositoryService', true],
        ], [
            'formulaRepository' => 'App\\Repository\\FormulaRepository',
        ]);
    }
}
