<?php

namespace ContainerIE5kwy1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TesxRYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._tesxRY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._tesxRY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'hoursRepository' => ['privates', 'App\\Repository\\HoursRepository', 'getHoursRepositoryService', true],
        ], [
            'hoursRepository' => 'App\\Repository\\HoursRepository',
        ]);
    }
}
