<?php

namespace ContainerQAccwrF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormulaRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\FormulaRepository' shared autowired service.
     *
     * @return \App\Repository\FormulaRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\FormulaRepository'] = new \App\Repository\FormulaRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
