<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKN3IRxh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKN3IRxh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKN3IRxh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKN3IRxh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKN3IRxh\App_KernelDevDebugContainer([
    'container.build_hash' => 'KN3IRxh',
    'container.build_id' => '310a12d0',
    'container.build_time' => 1677499127,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKN3IRxh');
