<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV6lD1UT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV6lD1UT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV6lD1UT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV6lD1UT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV6lD1UT\App_KernelDevDebugContainer([
    'container.build_hash' => 'V6lD1UT',
    'container.build_id' => '28d08e14',
    'container.build_time' => 1681378789,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV6lD1UT');
