<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.9a71ee5d.js',
                '/build/119.f9d81848.js',
                '/build/app.0fc63b66.js',
            ],
            'css' => [
                '/build/app.1a2874da.css',
            ],
        ],
    ],
],

]];
